"""
plan.py — GET /api/plan

Returns the farmer's care plan — from the server-side cache if the profile
is unchanged, or freshly generated by Gemini if the cache is stale/empty.
"""

import logging
import os
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from supabase import Client, create_client

from services.auth import get_user_id
from services.cache import compute_profile_hash
from services import planner, stage as stage_service

logger = logging.getLogger(__name__)

router = APIRouter()

# ── Supabase service-role client ──────────────────────────────────────────────
_SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
_SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")
if not _SUPABASE_URL or not _SUPABASE_SERVICE_KEY:
    raise RuntimeError(
        "SUPABASE_URL or SUPABASE_SERVICE_KEY environment variable is not set."
    )

_db: Client = create_client(_SUPABASE_URL, _SUPABASE_SERVICE_KEY)


# ── Response model ────────────────────────────────────────────────────────────

class PlanOut(BaseModel):
    stage_label: str
    months_elapsed: int
    plan_text: str
    from_cache: bool


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.get("/plan", response_model=PlanOut)
def get_plan(user_id: str = Depends(get_user_id)) -> PlanOut:
    """Return the farmer's care plan.

    Cache hit  (profile_hash unchanged, cached_plan not null) → returns immediately.
    Cache miss (hash changed or no cached plan) → calls Gemini, stores result.

    Returns 404 if no profile row exists (frontend redirects to onboarding).
    Returns 500 if Gemini is unavailable.
    """
    # ── 1. Fetch farmer row ───────────────────────────────────────────────────
    try:
        result = (
            _db.table("farmers")
            .select(
                "crop, plant_count, state, district, sowing_date, "
                "cached_plan, profile_hash"
            )
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
    except Exception as exc:
        logger.error("Supabase select failed: %s", exc)
        raise HTTPException(status_code=500, detail="Database error.")

    if result is None or not result.data:
        # No profile yet — tell the frontend to redirect to onboarding.
        raise HTTPException(status_code=404, detail="Profile not found.")

    row = result.data
    from datetime import date as date_type
    import datetime as dt_module

    sowing_date = (
        date_type.fromisoformat(row["sowing_date"])
        if isinstance(row["sowing_date"], str)
        else row["sowing_date"]
    )

    # ── 2. Check cache ────────────────────────────────────────────────────────
    current_hash = compute_profile_hash(
        row["crop"],
        row["plant_count"],
        row["state"],
        row["district"],
        sowing_date,
    )

    if current_hash == row.get("profile_hash") and row.get("cached_plan"):
        # Cache hit — compute months_elapsed and stage_label for the response.
        try:
            matched_stage, months_elapsed = stage_service.get_stage(
                row["crop"], sowing_date
            )
        except HTTPException:
            # sowing_date somehow in future — shouldn't happen, but handle gracefully.
            months_elapsed = 0
            matched_stage = {"label": row["crop"].title()}

        return PlanOut(
            stage_label=matched_stage["label"],
            months_elapsed=months_elapsed,
            plan_text=row["cached_plan"],
            from_cache=True,
        )

    # ── 3. Cache miss — generate fresh plan ───────────────────────────────────
    try:
        matched_stage, months_elapsed = stage_service.get_stage(
            row["crop"], sowing_date
        )
    except HTTPException as exc:
        # Future sowing_date slipped through — re-raise as-is.
        raise exc
    except KeyError as exc:
        logger.error("Unknown crop in stage lookup: %s", exc)
        raise HTTPException(status_code=422, detail="Crop not supported.")

    try:
        plan_text = planner.generate_plan(matched_stage, row["plant_count"])
    except RuntimeError:
        raise HTTPException(
            status_code=500,
            detail="Plan generation failed. Please try again later.",
        )

    # ── 4. Persist to cache ───────────────────────────────────────────────────
    now_utc = datetime.now(timezone.utc).isoformat()
    try:
        _db.table("farmers").update(
            {
                "cached_plan": plan_text,
                "profile_hash": current_hash,
                "plan_generated_at": now_utc,
            }
        ).eq("user_id", user_id).execute()
    except Exception as exc:
        # Non-fatal — return the plan even if caching fails; log the error.
        logger.error("Failed to persist cached plan: %s", exc)

    return PlanOut(
        stage_label=matched_stage["label"],
        months_elapsed=months_elapsed,
        plan_text=plan_text,
        from_cache=False,
    )
